### ISSUE TITLE
Use local Fonts for PDF generation

### ISSUE THREAD

**Issue by janstieler** [mpdf/mpdf.github.io#74]
Hi,
is it possible to use local fonts, I'mean not fonts in the mpdf font directory for the PDF generation?
I want to use arial or helvetica neue for generating, but for these fonts you need a license. Because of this I can't save it directly to the server.

I use version 6.7.

Cheers

**Comment by Klap-in** [comment]
Please have a look inthe manual at https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

Further, this issue looks at first glance more like troubleshooting. Please file troubleshoot and questions at https://stackoverflow.com/questions/tagged/mpdf

**Comment by janstieler** [comment]
I don't know if this is a troubleshoot or more ask to a function.
The manual does only talk about to put the fonts directly inside the mpdf folder and as I wrote is this no solution because of license restriction.

**Comment by danielhjames** [comment]
Hi Jan, at some point mPDF has to copy the fonts into its working directory in order to embed them in the PDF, whether that is from the server or your local machine. So if the problem is that your font does not allow copying without the payment of a license fee, you cannot work around this. The solution if you wish to embed a specific font is to pay for the font, or use a free software alternative such as DejaVu Sans. 

If you do not wish to embed, use the core fonts on the machine of the reader, but you will not be able to predict the exact appearance without end-user testing. See 'Core fonts' in https://mpdf.github.io/fonts-languages/font-substitution-7-x.html

If you work in many languages, you will find that DejaVu Sans has better coverage of glyphs than most proprietary fonts.

**Comment by janstieler** [comment]
Hi Daniel,
thanks for the explanation. I don't know that mPDF will copy the font into its working directory.
As I said, I want to use helvetica or arial than I think it should be possible to use corefonts.
I'll try.
The problem is that also for the arial you need a license if you want to use it. And the mots get it directly with the windows license. But this don't allow to use arial in different ways. And a arial license is not cheap :).

**Comment by danielhjames** [comment]
Hi Jan, it sounds like core fonts is the best option for you, it needs to be enabled explicitly in your mPDF configuration (see the link above). mPDF has to copy a font from somewhere if it is going to embed it. But if you have no embedding, you have no copying :-)

**Comment by janstieler** [comment]
Thanks the corefont function works fine!
